"""enable rls on agent tables

Revision ID: c586d296fc6e
Revises: 6dfb964c7ca9
Create Date: 2026-08-11 21:46:42.720803+00:00

Written by hand rather than autogenerated, because autogenerate only compares
*columns* against the models. Row-level security is not a column. Same
pattern as backend/alembic/versions/20260730_0900-a1c4e7b2f019_enable_rls_on_alembic_version.py.

Enabling RLS with no policies means deny-all for every role except the
table's owner (our own connection), which bypasses RLS. This is a backstop,
not the authorization mechanism - authorization is enforced in store.py's
callers, same division of labor as backend/'s services layer.
"""
from collections.abc import Sequence

from alembic import op

revision: str = "c586d296fc6e"
down_revision: str | None = "6dfb964c7ca9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    op.execute("ALTER TABLE agent.conversations ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE agent.messages ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    """Undo this migration."""
    op.execute("ALTER TABLE agent.messages DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE agent.conversations DISABLE ROW LEVEL SECURITY;")
