"""create agent tables

Revision ID: 6dfb964c7ca9
Revises: 
Create Date: 2026-08-11 21:36:42.516221+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identifiers Alembic uses to order migrations. `down_revision` pointing at the
# previous revision is what forms the chain; the first migration has None.
revision: str = '6dfb964c7ca9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('started_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='agent'
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider_data', sa.LargeBinary(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent.conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='agent'
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed `op.drop_table('products')` and
    # `op.drop_table('alembic_version')` here, because this env.py has no
    # include_schemas setting and the connection's default search_path is
    # `public` - autogenerate reflected public's tables and compared them
    # against target_metadata (agent.* only), reading them as "extra". Both
    # lines were removed by hand: this migration must never touch backend's
    # public schema. See docs/superpowers/plans/2026-08-12-gate-18-persistence.md
    # Task 7 for the permanent fix (include_schemas=False in backend's own
    # alembic/env.py, which is a different, unrelated file from this one).


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages', schema='agent')
    op.drop_table('conversations', schema='agent')
    # ### end Alembic commands ###
    # NOTE: the corresponding public.products/public.alembic_version
    # re-create blocks were removed for the same reason as upgrade() above.
