"""The ORM models - Python classes that describe database tables.

If you know Prisma, this file is `schema.prisma`, written in Python instead of
a bespoke DSL. Each class is a table; each `mapped_column` is a column. Alembic
reads these classes, compares them against the real database, and writes the
migration that closes the gap - the same job `prisma migrate dev` does.

The style below is SQLAlchemy **2.0**, which is worth flagging because most
tutorials online still show 1.x. The difference you will notice:

    # 1.x - the old way, still works, avoid it
    name = Column(String(200), nullable=False)

    # 2.0 - what we use
    name: Mapped[str] = mapped_column(String(200))

In 2.0 the *type annotation* carries the information. `Mapped[str]` means the
column is a non-nullable string; `Mapped[str | None]` means nullable. So
nullability is expressed once, in a place your type checker also reads, instead
of twice in two syntaxes that can disagree.
"""

from datetime import datetime, timezone
from decimal import Decimal
from typing import Any

from sqlalchemy import DateTime, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base
from core.enums import DraftStatus


class Product(Base):
    """A sellable item on the shelf.

    Slice 1 of the plan takes this one entity all the way through every layer -
    model, service, HTTP adapter, MCP adapter - so that the remaining entities
    have a concrete pattern to copy rather than a description of one.
    """

    # The physical table name. Without this, SQLAlchemy has no default and
    # raises. Plural, snake_case - the prevailing Postgres convention.
    __tablename__ = "products"

    # --- identity ----------------------------------------------------------

    # `primary_key=True` on a Mapped[int] gives us a Postgres SERIAL column -
    # an integer whose default is `nextval()` on an auto-created sequence
    # (`products_id_seq`). The database assigns the value; the attribute is
    # None in Python until the row is flushed.
    #
    # Postgres also offers the newer `GENERATED BY DEFAULT AS IDENTITY`, which
    # is standard SQL and ties the sequence's lifetime to the column. SERIAL is
    # what SQLAlchemy still emits by default and is entirely fine here; opting
    # in would mean `mapped_column(Identity(), primary_key=True)`.
    id: Mapped[int] = mapped_column(primary_key=True)

    # SKU - Stock Keeping Unit, the code on the shelf label. `unique=True`
    # creates a UNIQUE index, which is the real guarantee that no two products
    # share one. `index=True` is implied by unique, so we do not repeat it.
    #
    # `String(64)` becomes VARCHAR(64). The length is not enforcement theatre -
    # it documents intent and stops a bug writing a megabyte into the column.
    sku: Mapped[str] = mapped_column(String(64), unique=True)

    name: Mapped[str] = mapped_column(String(200))

    # `Mapped[str | None]` => NULL is allowed. Category is genuinely optional:
    # you can shelve a product before deciding where it belongs.
    category: Mapped[str | None] = mapped_column(String(100), default=None)

    # The unit stock is counted in - "piece", "kg", "litre", "box". Free text
    # for now; a lookup table if it ever needs constraining.
    unit: Mapped[str] = mapped_column(String(32), default="piece")

    # --- money -------------------------------------------------------------

    # Numeric(10, 2), NOT Float. This is the single most common data bug in
    # systems that handle money.
    #
    # A float is binary; 0.1 has no exact binary representation, the same way
    # 1/3 has no exact decimal one. Add 0.1 ten times in floats and you get
    # 0.9999999999999999. Over a day of supermarket transactions that drift
    # becomes a till that does not balance.
    #
    # Numeric is exact decimal arithmetic. Postgres stores it exactly, and
    # psycopg hands it back to Python as `decimal.Decimal` - which is why the
    # annotation is `Mapped[Decimal]` and not `Mapped[float]`. Be aware this
    # means `product.cost_price * 3` returns a Decimal, and mixing Decimal with
    # float in one expression raises. Keep money in Decimal end to end.
    #
    # (10, 2) = up to 10 total digits, 2 after the point: max 99,999,999.99.
    cost_price: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))
    sell_price: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))

    # --- stock -------------------------------------------------------------

    # Deliberately an int, not a Decimal: this counts whole units. Products
    # sold by weight are handled by choosing the unit ("gram" rather than "kg")
    # so the count stays integral.
    #
    # Note there is no CHECK constraint stopping this going negative. The rule
    # "stock may not go below zero" lives in `services/products.adjust_stock`,
    # because it needs to produce a message a human can act on. A database
    # CHECK is a reasonable belt-and-braces addition later; it is not the place
    # the rule is *expressed*.
    quantity_on_hand: Mapped[int] = mapped_column(default=0)

    # When quantity_on_hand falls to or below this, the product wants
    # reordering. Drives the "what should I buy today" view later.
    reorder_level: Mapped[int] = mapped_column(default=0)

    # --- audit -------------------------------------------------------------

    # `timezone=True` => TIMESTAMPTZ, not TIMESTAMP. Always use the former.
    # A bare TIMESTAMP stores a wall-clock reading with no indication of which
    # clock, so it is ambiguous the moment anything moves timezone or the
    # server does. TIMESTAMPTZ stores an unambiguous instant.
    #
    # `server_default=func.now()` puts the default in the DDL, so the *database*
    # supplies the value. Better than a Python default: it is one clock rather
    # than one per application process, and it still applies to rows inserted
    # by a migration or by hand in psql.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # `onupdate` is the counterpart, and this one *is* applied by SQLAlchemy in
    # Python on every UPDATE it issues. A raw SQL UPDATE run outside the ORM
    # would not trigger it - that would need a database trigger. Acceptable:
    # every write in this application goes through `services/`.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Who did it. Filled from `actor.id` by the service layer - see
    # core/actor.py. Nullable because rows can predate an actor being known
    # (a seed script, a manual fix), and String because the eventual auth
    # provider may hand us a UUID, an OIDC `sub`, or a name like "system".
    created_by: Mapped[str | None] = mapped_column(String(128), default=None)
    updated_by: Mapped[str | None] = mapped_column(String(128), default=None)

    # --- derived -----------------------------------------------------------

    @hybrid_property
    def needs_reorder(self) -> bool:
        """True when stock has fallen to or below the reorder level.

        This started life in the MCP adapter as a convenience for an agent
        asking "what needs restocking?". It was moved here on the grounds that
        it is a genuine business concept, not presentation: the definition of
        "needs reordering" is a rule the shop owns, and the purchasing service
        will need the same one. Defining it in an adapter would mean the web UI
        and the agent could one day disagree about what is running low - the
        exact failure the services-first design exists to prevent.

        **Why `hybrid_property` rather than a plain `@property`.** A plain
        property is computed in Python, on a row already loaded, so it can only
        be read after the fact:

            [p for p in all_products if p.needs_reorder]   # loads everything

        A hybrid works in *both* worlds. Used on an instance it runs the Python
        above; used on the class it emits SQL, so the same definition can filter
        in the database:

            select(Product).where(Product.needs_reorder)
            # -> WHERE products.quantity_on_hand <= products.reorder_level

        That matters the moment the catalogue is large enough that loading every
        row to find the low ones is the wrong shape of query. Writing it as a
        hybrid now costs one import and means the rule has exactly one
        definition serving both uses.

        No migration is needed: nothing is stored. This is computed from two
        columns that already exist, so the database schema is unchanged.
        """
        return self.quantity_on_hand <= self.reorder_level

    def __repr__(self) -> str:
        return f"Product(id={self.id!r}, sku={self.sku!r}, name={self.name!r})"


class ActionDraft(Base):
    """A proposed change, waiting for a human to approve it.

    The AI agent does not change prices, raise purchase orders or issue
    supplier credits. It writes down what it *wants* to do, with its reasoning
    and the money at stake, and a manager reads it and presses a button. See
    docs/FEATURES-PLAN.md, decision 1, for why this coexists with gate 19's
    in-conversation approval rather than replacing it: small single-item writes
    are confirmed in the chat, multi-item and financial ones come here.

    **`draft_type` is a name from a closed list, never a function.** The
    registry in `services/draft_types.py` maps it to one Pydantic schema and
    one hand-written handler. That is the whole security design of this gate.
    The feature set was specified with the payload carrying "target service
    function names and arguments"; resolving a function from a string held in a
    database row means anyone who can write a row can call anything with
    anything, so a row names a *type* and an unregistered type simply cannot
    run.
    """

    __tablename__ = "action_drafts"

    id: Mapped[int] = mapped_column(primary_key=True)

    # Not a Postgres ENUM type. A database enum needs a migration to add a
    # value, and gates 28-30 each add one; a checked string keeps that a
    # one-line change in Python. Nothing is lost, because the real gate is the
    # registry lookup, not the column type - an unknown string is refused
    # before it reaches the database on the way in, and before it reaches a
    # handler on the way out.
    draft_type: Mapped[str] = mapped_column(String(64), index=True)

    # Indexed because the approval queue's only query is "show me the pending
    # ones", and that is the query a human waits on.
    status: Mapped[str] = mapped_column(
        String(16), default=DraftStatus.PENDING, index=True
    )

    # JSONB rather than JSON: Postgres stores it decomposed instead of as text,
    # so it can be indexed and queried rather than only round-tripped. The
    # shape is decided per draft_type by that type's schema, deliberately not
    # by this column - three different proposal shapes share this one table,
    # which is the point of having a generic staging engine at all.
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB)

    # The agent's own words, for the human reading the card. `Text` rather than
    # `String(n)` because a model writing a summary should not hit a length
    # limit and get silently truncated mid-sentence - and this string is the
    # only thing the approver has to judge by.
    reasoning: Mapped[str] = mapped_column(Text)

    # --- the two money figures --------------------------------------------
    #
    # Two columns rather than one net figure, on purpose. "We saved 12,000" and
    # "we were about to lose 40,000 and recovered 12,000" are different
    # sentences to a manager, and a single number cannot tell them apart.
    #
    # Numeric(10, 2) for the reason spelled out on Product.cost_price: money in
    # a float drifts, and a till that does not balance is the bug you get.
    # Nullable because not every draft type has a financial dimension, and NULL
    # says "not applicable" where 0.00 would say "nothing at stake".
    cost_at_risk: Mapped[Decimal | None] = mapped_column(Numeric(10, 2), default=None)
    projected_recovery: Mapped[Decimal | None] = mapped_column(
        Numeric(10, 2), default=None
    )

    # NULL means "never expires". See DraftStatus for why this is a timestamp
    # compared on read rather than a status somebody has to write.
    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), default=None
    )

    # --- provenance --------------------------------------------------------

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Not nullable, unlike Product.created_by. A product row can predate anyone
    # knowing who made it; a draft cannot - it is created by exactly one call
    # that always has an actor, and a proposal with no proposer is not a thing
    # a human should be asked to approve.
    created_by: Mapped[str] = mapped_column(String(128))
    created_via: Mapped[str] = mapped_column(String(16))

    # NULL until somebody decides. `decided_via` records which door the
    # DECISION came through, which is usually not the door the proposal came
    # through - the agent proposes over MCP, a human approves in the browser,
    # and that difference is the entire feature.
    decided_by: Mapped[str | None] = mapped_column(String(128), default=None)
    decided_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), default=None
    )
    decided_via: Mapped[str | None] = mapped_column(String(16), default=None)

    @property
    def is_expired(self) -> bool:
        """True when this draft's deadline has passed.

        A plain `@property`, not a `hybrid_property` like `needs_reorder`
        above. The difference is deliberate: a hybrid also compiles to SQL, so
        the database can filter on it, which `needs_reorder` genuinely needs
        because the product list would otherwise load every row to find the low
        ones. Expiry does not need that - the pending queue is small by
        construction, since it is a list of things a human is about to read.
        Writing this as a hybrid would mean maintaining the rule twice, in
        Python and in SQL, for no benefit.

        `datetime.now(timezone.utc)` rather than `datetime.now()`: the column
        is TIMESTAMPTZ, so the value loaded back is timezone-aware, and Python
        raises TypeError when an aware and a naive datetime are compared. The
        naive version would pass every test on a UTC machine and fail on this
        developer's.
        """
        if self.expires_at is None:
            return False
        return datetime.now(timezone.utc) >= self.expires_at

    def __repr__(self) -> str:
        return (
            f"ActionDraft(id={self.id!r}, type={self.draft_type!r}, "
            f"status={self.status!r})"
        )
