"""The ORM models - Python classes that describe database tables.

If you know Prisma, this file is `schema.prisma`, written in Python instead of
a bespoke DSL. Each class is a table; each `mapped_column` is a column. Alembic
reads these classes, compares them against the real database, and writes the
migration that closes the gap - the same job `prisma migrate dev` does.

The style below is SQLAlchemy **2.0**, which is worth flagging because most
tutorials online still show 1.x. The difference you will notice:

    # 1.x - the old way, still works, avoid it
    name = Column(String(200), nullable=False)

    # 2.0 - what we use
    name: Mapped[str] = mapped_column(String(200))

In 2.0 the *type annotation* carries the information. `Mapped[str]` means the
column is a non-nullable string; `Mapped[str | None]` means nullable. So
nullability is expressed once, in a place your type checker also reads, instead
of twice in two syntaxes that can disagree.
"""

from datetime import datetime
from decimal import Decimal

from sqlalchemy import DateTime, Numeric, String, func
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base


class Product(Base):
    """A sellable item on the shelf.

    Slice 1 of the plan takes this one entity all the way through every layer -
    model, service, HTTP adapter, MCP adapter - so that the remaining entities
    have a concrete pattern to copy rather than a description of one.
    """

    # The physical table name. Without this, SQLAlchemy has no default and
    # raises. Plural, snake_case - the prevailing Postgres convention.
    __tablename__ = "products"

    # --- identity ----------------------------------------------------------

    # `primary_key=True` on a Mapped[int] gives us a Postgres SERIAL column -
    # an integer whose default is `nextval()` on an auto-created sequence
    # (`products_id_seq`). The database assigns the value; the attribute is
    # None in Python until the row is flushed.
    #
    # Postgres also offers the newer `GENERATED BY DEFAULT AS IDENTITY`, which
    # is standard SQL and ties the sequence's lifetime to the column. SERIAL is
    # what SQLAlchemy still emits by default and is entirely fine here; opting
    # in would mean `mapped_column(Identity(), primary_key=True)`.
    id: Mapped[int] = mapped_column(primary_key=True)

    # SKU - Stock Keeping Unit, the code on the shelf label. `unique=True`
    # creates a UNIQUE index, which is the real guarantee that no two products
    # share one. `index=True` is implied by unique, so we do not repeat it.
    #
    # `String(64)` becomes VARCHAR(64). The length is not enforcement theatre -
    # it documents intent and stops a bug writing a megabyte into the column.
    sku: Mapped[str] = mapped_column(String(64), unique=True)

    name: Mapped[str] = mapped_column(String(200))

    # `Mapped[str | None]` => NULL is allowed. Category is genuinely optional:
    # you can shelve a product before deciding where it belongs.
    category: Mapped[str | None] = mapped_column(String(100), default=None)

    # The unit stock is counted in - "piece", "kg", "litre", "box". Free text
    # for now; a lookup table if it ever needs constraining.
    unit: Mapped[str] = mapped_column(String(32), default="piece")

    # --- money -------------------------------------------------------------

    # Numeric(10, 2), NOT Float. This is the single most common data bug in
    # systems that handle money.
    #
    # A float is binary; 0.1 has no exact binary representation, the same way
    # 1/3 has no exact decimal one. Add 0.1 ten times in floats and you get
    # 0.9999999999999999. Over a day of supermarket transactions that drift
    # becomes a till that does not balance.
    #
    # Numeric is exact decimal arithmetic. Postgres stores it exactly, and
    # psycopg hands it back to Python as `decimal.Decimal` - which is why the
    # annotation is `Mapped[Decimal]` and not `Mapped[float]`. Be aware this
    # means `product.cost_price * 3` returns a Decimal, and mixing Decimal with
    # float in one expression raises. Keep money in Decimal end to end.
    #
    # (10, 2) = up to 10 total digits, 2 after the point: max 99,999,999.99.
    cost_price: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))
    sell_price: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))

    # --- stock -------------------------------------------------------------

    # Deliberately an int, not a Decimal: this counts whole units. Products
    # sold by weight are handled by choosing the unit ("gram" rather than "kg")
    # so the count stays integral.
    #
    # Note there is no CHECK constraint stopping this going negative. The rule
    # "stock may not go below zero" lives in `services/products.adjust_stock`,
    # because it needs to produce a message a human can act on. A database
    # CHECK is a reasonable belt-and-braces addition later; it is not the place
    # the rule is *expressed*.
    quantity_on_hand: Mapped[int] = mapped_column(default=0)

    # When quantity_on_hand falls to or below this, the product wants
    # reordering. Drives the "what should I buy today" view later.
    reorder_level: Mapped[int] = mapped_column(default=0)

    # --- audit -------------------------------------------------------------

    # `timezone=True` => TIMESTAMPTZ, not TIMESTAMP. Always use the former.
    # A bare TIMESTAMP stores a wall-clock reading with no indication of which
    # clock, so it is ambiguous the moment anything moves timezone or the
    # server does. TIMESTAMPTZ stores an unambiguous instant.
    #
    # `server_default=func.now()` puts the default in the DDL, so the *database*
    # supplies the value. Better than a Python default: it is one clock rather
    # than one per application process, and it still applies to rows inserted
    # by a migration or by hand in psql.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # `onupdate` is the counterpart, and this one *is* applied by SQLAlchemy in
    # Python on every UPDATE it issues. A raw SQL UPDATE run outside the ORM
    # would not trigger it - that would need a database trigger. Acceptable:
    # every write in this application goes through `services/`.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Who did it. Filled from `actor.id` by the service layer - see
    # core/actor.py. Nullable because rows can predate an actor being known
    # (a seed script, a manual fix), and String because the eventual auth
    # provider may hand us a UUID, an OIDC `sub`, or a name like "system".
    created_by: Mapped[str | None] = mapped_column(String(128), default=None)
    updated_by: Mapped[str | None] = mapped_column(String(128), default=None)

    def __repr__(self) -> str:
        return f"Product(id={self.id!r}, sku={self.sku!r}, name={self.name!r})"
