import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * The architecture rules are the point of this file.
 *
 * The backend's credibility comes from one mechanical rule — `services/` never
 * imports from `api/` or `mcp_server/`, enforced by `import-linter` rather than
 * by good intentions. These blocks are the frontend's equivalent. Both rules
 * are stated in `docs/FRONTEND-PLAN.md`; this is where they are enforced.
 *
 * They are `error`, not `warn`, deliberately. A warning is a rule that has
 * already been broken and nobody noticed.
 */
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run api:types` from the backend's /openapi.json.
    // Committed so drift is a reviewable diff, never hand-edited, and there is
    // nothing to gain from linting it. See docs/FRONTEND-PLAN.md.
    "src/lib/api/schema.d.ts",
  ]),

  /**
   * Rule 1 — only `src/lib/api` talks to the network.
   *
   * The UI is a client of the API and nothing more. If any component may call
   * `fetch`, request logic spreads across the tree, the base URL gets read in
   * six places, and error handling is reinvented per screen. One module owns
   * the transport; everything else imports from it.
   */
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/lib/api/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "openapi-fetch",
              message:
                "Only src/lib/api may construct an API client. Import { api } from '@/lib/api/client' instead.",
            },
            {
              name: "server-only",
              // Not an architecture rule — a correctness one. This module is a
              // marker that makes bundling into client code a build error; it
              // belongs on modules that hold secrets or server state, not
              // sprinkled through the UI where it just breaks Client Components.
              message:
                "server-only marks transport and identity modules under src/lib. Components should not import it.",
            },
          ],
          patterns: [
            {
              group: ["**/lib/api/schema", "**/lib/api/schema.d"],
              message:
                "schema.d.ts is generated build output. Import types from '@/lib/api/client', which re-exports them.",
            },
          ],
        },
      ],
      "no-restricted-globals": [
        "error",
        {
          name: "fetch",
          message:
            "Only src/lib/api may call fetch. Use the typed client from '@/lib/api/client'.",
        },
      ],
    },
  },

  /**
   * Rule 2 — no route handlers mirroring FastAPI.
   *
   * A Next route handler that proxies `/products` to FastAPI is a *third
   * adapter* — the same category of mistake as `services/` importing `api/`,
   * and forbidden for the same reason: the same operation would then exist in
   * three places and drift in two of them. React Server Components call FastAPI
   * directly; Next's own documentation calls the mirror layer an anti-pattern.
   *
   * `Program` matches the top of every file, so this rejects the existence of
   * any module in the tree rather than any particular thing it does. If a real
   * need for a route handler ever appears — a webhook receiver, an OAuth
   * callback, neither of which mirrors an endpoint — this rule is the place to
   * carve out that exception explicitly, with the reason written down.
   */
  {
    files: ["src/app/api/**"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "Program",
          message:
            "No route handlers under src/app/api — that would be a third adapter mirroring FastAPI. Server Components call the API directly. See docs/FRONTEND-PLAN.md.",
        },
      ],
    },
  },
]);

export default eslintConfig;
