/**
 * The one place this app talks to FastAPI.
 *
 * Everything outside `src/lib/api` imports from here rather than calling
 * `fetch` itself — enforced by ESLint `no-restricted-imports` /
 * `no-restricted-globals` in `eslint.config.mjs`, which is the frontend's
 * answer to the backend's `lint-imports`. A rule nobody can accidentally break
 * is worth more than a rule everyone agrees with.
 *
 * The types come from `./schema` — generated by `npm run api:types` from the
 * backend's own `/openapi.json`, never hand-written. See `docs/FRONTEND-PLAN.md`
 * for why the generated file is committed.
 */
import "server-only";

import createClient from "openapi-fetch";

import type { paths } from "./schema";

/**
 * Base URL of the FastAPI adapter.
 *
 * Read at module load and asserted, so a missing `.env.local` fails once, at
 * startup, with a message naming the variable — rather than surfacing later as
 * a fetch to `undefined/products` that reads like a network problem.
 *
 * No `NEXT_PUBLIC_` prefix, deliberately: this value never reaches the browser.
 * See `frontend/.env.example`.
 */
const baseUrl = process.env.API_BASE_URL;

if (!baseUrl) {
  throw new Error(
    "API_BASE_URL is not set. Copy frontend/.env.example to .env.local. " +
      "The dev default matches `uvicorn api.main:app --reload` run from backend/.",
  );
}

/**
 * The typed client. `paths` is the generated description of every endpoint, so
 * `api.GET("/products", ...)` autocompletes its query parameters and knows the
 * response shape; a path or field the backend does not have is a compile error.
 */
export const api = createClient<paths>({ baseUrl });

/**
 * Re-exported so call sites can name a response type without reaching into the
 * generated file themselves — `schema.d.ts` is build output, and the fewer
 * modules that know its internal shape, the cheaper a regeneration is.
 */
export type { components, paths } from "./schema";
