/**
 * This file was automatically generated from src/lib/api/mcp-schema.json.
 * DO NOT MODIFY IT BY HAND. Instead, run `npm run mcp:types` to regenerate this file.
 */

/**
 * Generated by backend/mcp_server/dump_schemas.py - do not edit.
 */
export interface MCPToolOutputs {
  adjust_stock: ProductOut;
  check_spoilage_risk: SpoilageReportOut;
  create_action_draft: DraftOut;
  create_product: ProductOut;
  get_product: ProductOut;
  get_product_by_sku: ProductOut;
  list_pending_drafts: DraftListOut;
  list_product_lots: LotListOut;
  list_products: ProductListOut;
  list_purchase_orders: PurchaseOrderListOut;
  propose_delivery_receipt: DraftOut;
  propose_reorder_order: DraftOut;
  propose_spoilage_markdown: DraftOut;
  receive_stock_lot: LotOut;
  suggest_reorder_bundles: ReorderReportOut;
  update_product: ProductOut;
}
export interface ProductOut {
  category: string | null;
  cost_price: string;
  id: number;
  name: string;
  needs_reorder: boolean;
  quantity_on_hand: number;
  reorder_level: number;
  sell_price: string;
  sku: string;
  unit: string;
  updated_by: string | null;
}
export interface SpoilageReportOut {
  items: SpoilageItemOut[];
  scanned_on: string;
  total_cost_at_risk: string;
  total_projected_recovery: string;
  within_days: number;
}
export interface SpoilageItemOut {
  cost_at_risk: string;
  current_price: string;
  days_remaining: number;
  discount_percent: number;
  expiry_date: string;
  lot_code: string;
  lot_id: number;
  product_id: number;
  product_name: string;
  projected_recovery: string;
  proposed_price: string;
  quantity: number;
  sku: string;
  why: string;
}
export interface DraftOut {
  cost_at_risk: string | null;
  created_by: string | null;
  created_via: string;
  decided_by: string | null;
  decided_via: string | null;
  draft_type: string;
  expires_at: string | null;
  id: number;
  is_expired: boolean;
  payload: {
    [k: string]: unknown;
  };
  projected_recovery: string | null;
  reasoning: string;
  status: string;
}
export interface DraftListOut {
  drafts: DraftOut[];
}
export interface LotListOut {
  lots: LotOut[];
}
export interface LotOut {
  cost_price: string;
  discount_percent: number;
  expiry_date: string | null;
  is_expired: boolean;
  lot_code: string;
  lot_id: number;
  product_id: number;
  quantity: number;
  sell_price: string;
}
export interface ProductListOut {
  products: ProductOut[];
  total: number;
}
export interface PurchaseOrderListOut {
  orders: PurchaseOrderOut[];
  total: number;
}
export interface PurchaseOrderOut {
  created_by: string | null;
  expected_date: string | null;
  id: number;
  lines: POLineOut[];
  notes: string | null;
  source_draft_id: number | null;
  status: string;
  supplier_id: number;
  total_value: string;
}
export interface POLineOut {
  line_total: string;
  product_id: number;
  quantity_ordered: number;
  unit_cost: string;
}
export interface ReorderReportOut {
  bundles: ReorderBundleOut[];
  total_value: string;
  unsourced: UnsourcedOut[];
}
export interface ReorderBundleOut {
  below_minimum: boolean;
  bundle_value: string;
  lead_time_days: number;
  lines: ReorderLineOut[];
  minimum_order_value: string;
  shortfall: string;
  supplier_id: number;
  supplier_name: string;
}
export interface ReorderLineOut {
  is_top_up: boolean;
  line_total: string;
  name: string;
  pack_size: number;
  product_id: number;
  quantity: number;
  quantity_on_hand: number;
  reorder_level: number;
  sku: string;
  unit_cost: string;
}
export interface UnsourcedOut {
  name: string;
  product_id: number;
  quantity_on_hand: number;
  reorder_level: number;
  sku: string;
}
