/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description List products, newest first, optionally filtered by a search term.
         *
         *     Docstrings on these functions are not only for developers: FastAPI puts them
         *     into the OpenAPI document, so this text appears in the /docs page. It is the
         *     same trick the MCP adapter will use in Gate 6, where the docstring becomes
         *     the tool description an AI model reads to decide whether to call it.
         *
         *     `response_model=ProductList` does two jobs. It documents the shape in
         *     OpenAPI, and it *filters* the output: even if the service returned an object
         *     with extra attributes, only the fields declared on ProductRead are
         *     serialised. That is the guarantee that makes returning ORM objects safe.
         *
         *     Pagination: `{items, total}`, where `total` counts everything matching
         *     `search` regardless of the window. That costs a second COUNT query on every
         *     list call, which is the honest price of page numbers - an offset-based
         *     control cannot render "of 12 pages" without knowing there are 12.
         *
         *     The two calls are deliberately separate service functions rather than one
         *     returning a pair, so the MCP adapter - where an agent has no use for a page
         *     total - does not pay for the COUNT. See `services/products.py`.
         */
        get: operations["list_products_products_get"];
        put?: never;
        /**
         * Create Product
         * @description Create a product.
         *
         *     `payload: ProductCreate` is how FastAPI knows to read the request *body*:
         *     the parameter's type is a Pydantic model, so it cannot be a path or query
         *     parameter. Path, query and body are distinguished by type, not by decorator.
         *
         *     `status_code=201` because a POST that creates a resource should say so. The
         *     default would be 200, which is not wrong so much as uninformative.
         *
         *     `**payload.model_dump()` unpacks the model's fields into keyword arguments -
         *     `sku=..., name=..., cost_price=...`. It works precisely because the schema's
         *     field names were chosen to match the service's parameter names, and because
         *     every one of those parameters is keyword-only. Spelling all eight out by
         *     hand would be more explicit but would rot: adding a field to the schema and
         *     forgetting it here would silently drop it.
         */
        post: operations["create_product_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/by-sku/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product By Sku
         * @description Look a product up by the code on its shelf label.
         *
         *     This route is declared *before* `/{product_id}` on purpose. FastAPI matches
         *     in declaration order, and `/products/by-sku/X` has two segments where
         *     `/products/{product_id}` has one, so there is no real collision here - but
         *     the habit matters: a literal path that could be mistaken for a parameter
         *     must come first, or the parameterised route swallows it.
         */
        get: operations["get_product_by_sku_products_by_sku__sku__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product
         * @description Fetch a single product by id.
         *
         *     Missing row -> the service raises `NotFoundError` -> api/errors.py turns it
         *     into a 404. Nothing in this function knows any of that happened.
         */
        get: operations["get_product_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Product
         * @description Update the fields that were supplied, leaving the rest alone.
         *
         *     PATCH rather than PUT, and `exclude_unset=True` is what makes that true - it
         *     drops any field the client did not send, so the service receives only the
         *     ones actually being changed. Without it, every omitted field would arrive as
         *     an explicit `None` and the service would read that as "clear this value",
         *     wiping the category off any product updated with a price change.
         */
        patch: operations["update_product_products__product_id__patch"];
        trace?: never;
    };
    "/products/{product_id}/adjust-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjust Stock
         * @description Move stock by a signed amount: `+12` received, `-3` damaged.
         *
         *     Not a PATCH on `quantity_on_hand`, and the distinction is the point. A stock
         *     level is not an editable field, it is the consequence of events. Modelling
         *     it as an action keeps the *reason* attached and leaves room for
         *     services/inventory.py to record a ledger row per movement later, without any
         *     change to this endpoint's contract.
         *
         *     Refusing to go negative is the service's rule, and it produces a message
         *     naming the actual shortfall. It reaches the client as a **400**, not a 422 -
         *     `ValidationError` was moved off 422 precisely so a shopkeeper-readable "only
         *     2 in stock" is not behind the same code as a malformed request body. See
         *     core/exceptions.py.
         */
        post: operations["adjust_stock_products__product_id__adjust_stock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check that actually proves something.
         *
         *     Returning a hardcoded `{"status": "ok"}` would confirm only that the Python
         *     process is running - which the response itself already proved. This runs
         *     `SELECT 1` against Postgres, so a green answer means the app can reach its
         *     database. That is the failure this endpoint exists to catch: Supabase asleep,
         *     credentials rotated, network gone.
         *
         *     `text("SELECT 1")` is required because SQLAlchemy 2.0 refuses to execute a
         *     bare string. It is a deliberate speed bump against accidentally passing a
         *     formatted string - the shortest path to SQL injection - so raw SQL has to be
         *     marked as intentional.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorResponse
         * @description The shape of every error this API returns.
         *
         *     Declared as a schema so it shows up in the OpenAPI document, which means the
         *     frontend can generate a typed client for the failure cases too - not just
         *     the happy path. See api/errors.py for what fills it in.
         */
        ErrorResponse: {
            /**
             * Error
             * @description Machine-readable class, e.g. 'NotFoundError'.
             * @enum {string}
             */
            error: "NotFoundError" | "DuplicateError" | "ValidationError" | "PermissionDeniedError" | "DomainError" | "RequestValidationError" | "RouteNotFound" | "MethodNotAllowed" | "NotAuthenticated" | "HTTPError";
            /**
             * Detail
             * @description Human-readable message, safe to show a user.
             */
            detail: string;
            /**
             * Fields
             * @description Field name -> message. Present on 422 only.
             */
            fields?: {
                [key: string]: string;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ProductCreate
         * @description The body of POST /products.
         *
         *     `Field(...)` attaches constraints and documentation to a field. The
         *     constraints here are *structural* - things that can be checked by looking at
         *     the value alone, with no database and no context: is it a string, is it
         *     short enough, is it non-negative.
         *
         *     Business rules stay in `services/products.py`. "This SKU is already taken"
         *     cannot be checked here because it needs a query, and "stock may not go
         *     negative" cannot be checked here because it needs the current stock. That
         *     split is the important one: Pydantic guards the shape, the service guards
         *     the meaning. Duplicating a service rule here would mean the MCP adapter,
         *     which never sees this file, silently loses it.
         *
         *     Note the deliberate redundancy on prices: `ge=0` here *and* a check in the
         *     service. The service one is authoritative and covers both adapters; this one
         *     exists so an HTTP client gets a clean field-level 422 instead of a 400.
         */
        ProductCreate: {
            /**
             * Sku
             * @description Shelf label code.
             */
            sku: string;
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /**
             * Unit
             * @default piece
             */
            unit: string;
            /**
             * Cost Price
             * @default 0.00
             */
            cost_price: number | string;
            /**
             * Sell Price
             * @default 0.00
             */
            sell_price: number | string;
            /**
             * Quantity On Hand
             * @description Opening stock.
             * @default 0
             */
            quantity_on_hand: number;
            /**
             * Reorder Level
             * @default 0
             */
            reorder_level: number;
        };
        /**
         * ProductList
         * @description The body of GET /products: a page of results plus the size of the whole set.
         *
         *     `items` alone was the original shape, and it cannot support page numbers -
         *     "page 3 of 12" needs to know there are 12. The total arrives as a body
         *     field rather than an `X-Total-Count` header because `openapi-typescript`
         *     generates precise types for bodies and near-useless ones for headers, and
         *     the frontend's whole contract-safety story rests on that generator.
         *
         *     Note `total` counts every product matching the current `search`, ignoring
         *     `limit` and `offset`. A total that respected the window would just be
         *     `len(items)`.
         */
        ProductList: {
            /** Items */
            items: components["schemas"]["ProductRead"][];
            /**
             * Total
             * @description Total matching the search, ignoring limit/offset.
             */
            total: number;
        };
        /**
         * ProductRead
         * @description What every product endpoint returns.
         *
         *     `from_attributes=True` is the line that makes this work with the ORM. By
         *     default Pydantic builds a model from a dict; with this set it will also read
         *     plain attributes off an arbitrary object, so a SQLAlchemy `Product` can be
         *     handed straight to it. FastAPI does that conversion automatically when this
         *     class is the declared `response_model`.
         *
         *     (In Pydantic v1 this setting was called `orm_mode`. Tutorials showing that
         *     name, or a `class Config:` block instead of `model_config`, are v1 - the
         *     single most common source of copy-paste failure when learning this stack.)
         *
         *     Every field listed here is a deliberate decision to make it public. The
         *     audit columns are included because an inventory manager genuinely wants to
         *     know who last touched a row; `created_by` would be omitted if it held
         *     anything sensitive.
         */
        ProductRead: {
            /** Id */
            id: number;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Unit */
            unit: string;
            /** Cost Price */
            cost_price: string;
            /** Sell Price */
            sell_price: string;
            /** Quantity On Hand */
            quantity_on_hand: number;
            /** Reorder Level */
            reorder_level: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Created By */
            created_by: string | null;
            /** Updated By */
            updated_by: string | null;
            /**
             * Needs Reorder
             * @description True when quantity_on_hand <= reorder_level.
             */
            needs_reorder: boolean;
        };
        /**
         * ProductUpdate
         * @description The body of PATCH /products/{id}. Every field optional.
         *
         *     This mirrors `update_product`'s signature exactly, including its known
         *     limitation: `None` means "not supplied, leave alone", so there is currently
         *     no way to clear `category` back to NULL through this endpoint. Fixing that
         *     needs a sentinel value distinct from None, and it is not worth the machinery
         *     until something actually needs to clear a field.
         *
         *     `sku` and `quantity_on_hand` are absent by design. An SKU is printed on
         *     shelf labels, so changing it is a bigger event than a PATCH. Stock moves
         *     only through the adjust endpoint, so that a reason stays attached to it.
         */
        ProductUpdate: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Unit */
            unit?: string | null;
            /** Cost Price */
            cost_price?: number | string | null;
            /** Sell Price */
            sell_price?: number | string | null;
            /** Reorder Level */
            reorder_level?: number | null;
        };
        /**
         * StockAdjustment
         * @description The body of POST /products/{id}/adjust-stock.
         *
         *     A signed delta, not a new total. "Three cases arrived" and "we counted and
         *     there are 47" are different events, and a delta records the first honestly.
         *     A stock-take that sets an absolute figure is a separate operation, and it
         *     belongs in `services/inventory.py` when that exists.
         */
        StockAdjustment: {
            /**
             * Delta
             * @description Signed change: +12 received, -3 damaged.
             */
            delta: number;
            /** Reason */
            reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_products_products_get: {
        parameters: {
            query?: {
                /** @description Matches name or SKU. */
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description The actor lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body does not match the schema. Carries `fields`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_product_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description A business rule was broken. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The actor lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description That SKU is already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body does not match the schema. Carries `fields`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_product_by_sku_products_by_sku__sku__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description The actor lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such product. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description The actor lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such product. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body does not match the schema. Carries `fields`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_product_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description A business rule was broken. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The actor lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such product. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body does not match the schema. Carries `fields`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adjust_stock_products__product_id__adjust_stock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockAdjustment"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description A business rule was broken. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The actor lacks the required permission. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such product. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request body does not match the schema. Carries `fields`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
