"""create credit memos table

Revision ID: 34334348fe8e
Revises: 276428c7f1dd
Create Date: 2026-08-27 18:06:57.170701+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# Identifiers Alembic uses to order migrations. `down_revision` pointing at the
# previous revision is what forms the chain; the first migration has None.
revision: str = '34334348fe8e'
down_revision: str | None = '276428c7f1dd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('created_via', sa.String(length=16), nullable=False),
    sa.Column('source_draft_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_memos_purchase_order_id'), 'credit_memos', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_credit_memos_supplier_id'), 'credit_memos', ['supplier_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("ALTER TABLE credit_memos ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Undo this migration."""
    op.execute("ALTER TABLE credit_memos DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_memos_supplier_id'), table_name='credit_memos')
    op.drop_index(op.f('ix_credit_memos_purchase_order_id'), table_name='credit_memos')
    op.drop_table('credit_memos')
    # ### end Alembic commands ###
