"""create action_drafts table

Revision ID: c3f81d5a24b7
Revises: a1c4e7b2f019
Create Date: 2026-08-27 15:00:00.000000+00:00

Gate 27. The staging queue: the agent writes down what it wants to do, and a
human approves it. See docs/FEATURES-PLAN.md.

Written by hand rather than autogenerated, for the same reason the RLS
migration before it was. `alembic revision --autogenerate` compares *columns*
against the models, so it would produce the `create_table` correctly and
silently omit the `ENABLE ROW LEVEL SECURITY` at the bottom - row-level
security is not a column. A migration that creates a table and leaves it
world-writable is exactly the failure this project's advisor caught once
already, so the two statements are kept together in one file where they cannot
drift apart.

Note there is no foreign key on this table. A draft's payload refers to
products (and, from gate 29, to suppliers and purchase orders) by id *inside*
the JSONB, deliberately: three different proposal shapes share this table, and
a column that is a foreign key for one draft type and meaningless for another
is not a constraint, it is a nullable integer with a misleading name. The
handler resolves and validates those ids when the draft is approved, which is
also the only moment the reference has to still be valid.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Identifiers Alembic uses to order migrations. `down_revision` points at the
# previous head, which is the RLS migration from gate 2.
revision: str = "c3f81d5a24b7"
down_revision: str | None = "a1c4e7b2f019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    op.create_table(
        "action_drafts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("draft_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        # JSONB rather than JSON: stored decomposed, so it can be indexed and
        # queried rather than only round-tripped as text.
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        # Numeric(10, 2) and never a float - see core/models.py on why money in
        # binary floating point eventually stops balancing. Nullable because
        # NULL says "this draft type has no financial dimension", which is a
        # different fact from 0.00 meaning "nothing is at stake".
        sa.Column("cost_at_risk", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "projected_recovery", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        # TIMESTAMPTZ. NULL means "never expires". Nothing writes an EXPIRED
        # status - whether this moment has passed is computed on read, because
        # this project has no scheduler to do the writing.
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # NOT NULL, unlike products.created_by. A product row can predate
        # anyone knowing who made it; a draft is created by exactly one call
        # that always carries an actor, and a proposal with no proposer is not
        # something a human should be asked to approve.
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_via", sa.String(length=16), nullable=False),
        # NULL until somebody decides. `decided_via` is usually a different
        # door from `created_via` - the agent proposes over MCP, a human
        # approves in the browser - and that difference is the whole feature.
        sa.Column("decided_by", sa.String(length=128), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_via", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Both indexed because the approval queue's only real query is "the pending
    # ones, newest first", and that is a query a human is sitting waiting on.
    op.create_index(
        op.f("ix_action_drafts_draft_type"), "action_drafts", ["draft_type"]
    )
    op.create_index(op.f("ix_action_drafts_status"), "action_drafts", ["status"])

    # Deny-all backstop, matching every other table in this schema. Real
    # authorization is enforced in services/ via actor.can(...) - RLS exists so
    # that a future bug, or a leaked publishable key, cannot read or write these
    # rows silently. Our own connection is unaffected: the table owner bypasses
    # RLS. Without this, PostgREST publishes the table and anyone holding the
    # anon key could approve their own drafts.
    op.execute("ALTER TABLE action_drafts ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    """Undo this migration."""
    op.execute("ALTER TABLE action_drafts DISABLE ROW LEVEL SECURITY;")
    op.drop_index(op.f("ix_action_drafts_status"), table_name="action_drafts")
    op.drop_index(op.f("ix_action_drafts_draft_type"), table_name="action_drafts")
    op.drop_table("action_drafts")
