"""create inventory_lots table and backfill one lot per product

Revision ID: d5b93a17c204
Revises: c3f81d5a24b7
Create Date: 2026-08-27 18:30:00.000000

Hand-written rather than autogenerated, for two reasons that autogenerate
cannot know about:

  1. **Row Level Security.** Alembic's autogenerate compares ORM models against
     the database and writes the difference. RLS is not part of the model, so
     it never appears in a generated migration - the table would arrive
     unprotected and nothing would say so. Every table in this schema has RLS
     enabled as a backstop (deny-all, no policies), so that a future bug or a
     leaked connection string cannot read or write silently. Authorization
     itself is enforced in `services/`, not in policies.

  2. **The backfill.** Products already have stock and no lots. From the moment
     this table exists, `services/lots.py` treats lots as the source of truth
     and `products.quantity_on_hand` as a summary of them - so a product with
     stock and no lots is a contradiction the system would report as "0 in
     stock" on any lot-aware screen while the product row says 40.

     The backfill closes that gap in the same transaction that opens it.

### What the backfilled lots mean

One lot per product that currently has stock, holding that exact quantity,
with **`expiry_date` NULL**. NULL means "we do not know", which is the honest
answer for stock that was on the shelf before the shop tracked expiry dates.

⚠️ The spoilage scan **skips** lots with no expiry date rather than guessing.
That is the whole point of the NULL: unknown stock can never trigger a
markdown, so the first thing this feature does on a real shop's data is
nothing, until real deliveries with real dates start arriving.

`lot_code` is `'OPENING'` and `created_by` is `'system'` so these rows are
identifiable forever as the ones the migration invented rather than ones a
person or an agent received.

### Downgrade

Drops the table. The backfilled quantities are not lost by that, because
`products.quantity_on_hand` is never modified here - it is left holding the
same number it held before, which is exactly the sum of the lots created. So
downgrading returns the database to a consistent earlier state rather than a
damaged one.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "d5b93a17c204"
down_revision: Union[str, Sequence[str], None] = "c3f81d5a24b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "inventory_lots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("lot_code", sa.String(length=64), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("cost_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("updated_by", sa.String(length=128), nullable=True),
        sa.Column("created_via", sa.String(length=16), nullable=False),
        sa.Column("source_draft_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Two indexes, each earning its place:
    #
    #   product_id  - every lot query starts "the lots for this product".
    #   expiry_date - the spoilage scan sweeps the whole table asking "what
    #                 expires within N days", which is a range scan across
    #                 every product at once.
    op.create_index(
        op.f("ix_inventory_lots_product_id"), "inventory_lots", ["product_id"]
    )
    op.create_index(
        op.f("ix_inventory_lots_expiry_date"), "inventory_lots", ["expiry_date"]
    )

    # See the module docstring. Autogenerate will never write this line.
    op.execute("ALTER TABLE inventory_lots ENABLE ROW LEVEL SECURITY;")

    # --- the backfill ------------------------------------------------------
    #
    # `WHERE quantity_on_hand > 0` so products with no stock do not get a
    # pointless zero-quantity lot. `cost_price` is copied from the product,
    # which is the best available estimate of what this stock cost - the real
    # figure was never recorded, and a lot's cost_price is a copy by design so
    # that later price changes cannot rewrite history.
    op.execute(
        """
        INSERT INTO inventory_lots (
            product_id, lot_code, expiry_date, quantity, cost_price,
            created_by, created_via
        )
        SELECT id, 'OPENING', NULL, quantity_on_hand, cost_price,
               'system', 'system'
        FROM products
        WHERE quantity_on_hand > 0;
        """
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_inventory_lots_expiry_date"), table_name="inventory_lots")
    op.drop_index(op.f("ix_inventory_lots_product_id"), table_name="inventory_lots")
    op.drop_table("inventory_lots")
