"""create products table

Revision ID: 068702c8e737
Revises: 
Create Date: 2026-07-30 08:38:49.954619+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# Identifiers Alembic uses to order migrations. `down_revision` pointing at the
# previous revision is what forms the chain; the first migration has None.
revision: str = '068702c8e737'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )

    op.execute("ALTER TABLE products ENABLE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE products DISABLE ROW LEVEL SECURITY;")
    op.drop_table('products')
    # ### end Alembic commands ###
