"""enable rls on alembic_version

Revision ID: a1c4e7b2f019
Revises: 068702c8e737
Create Date: 2026-07-30 09:00:00.000000+00:00

Written by hand rather than autogenerated, because autogenerate only compares
*columns* against the models. Row-level security is not a column, and
alembic_version is not one of our models - it is Alembic's own bookkeeping
table, holding the revision hash of the last migration applied.

Supabase's `get_advisors` flagged it as critical: PostgREST publishes every
table in the `public` schema, so with RLS off, anyone holding the publishable
("anon") key can UPDATE or DELETE that row. Reading it leaks only a hash, but
writing it breaks migrations - clear the row and the next `alembic upgrade`
tries to create tables that already exist; set it to a hash that does not
exist and Alembic refuses to run at all.

Enabling RLS with no policies means deny-all for the anon and authenticated
roles. Our own connection is unaffected, because the table's owner bypasses RLS.
"""
from collections.abc import Sequence

from alembic import op

revision: str = "a1c4e7b2f019"
down_revision: str | None = "068702c8e737"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    op.execute("ALTER TABLE alembic_version ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    """Undo this migration."""
    op.execute("ALTER TABLE alembic_version DISABLE ROW LEVEL SECURITY;")
