"""Emit the MCP tool-output JSON Schema the frontend generates types from.

    python -m mcp_server.dump_schemas

writes `frontend/src/lib/api/mcp-schema.json` - one document, every tool-output
model under `$defs`, and a top-level object whose properties map each tool name
to a `$ref`. `npm run mcp:types` (frontend) turns that into `mcp-types.d.ts`.

Pure model introspection: no server, no database, no auth. The counterpart of
`npm run api:types` for the REST client, except the source is Pydantic models
rather than a running FastAPI's /openapi.json - so this runs anywhere, and the
drift check is a plain file diff instead of "boot a server first".

Deterministic output (sorted keys, 2-space indent, trailing newline) so
`git diff --exit-code` on the committed file is a valid CI check.
`tests/test_mcp_schemas.py::test_committed_schema_matches_the_models` is the
same check inside pytest, so it runs in CI's existing backend job with no npm.
"""

from __future__ import annotations

import json
from pathlib import Path

from pydantic.json_schema import GenerateJsonSchema, models_json_schema

from mcp_server.schemas import TOOL_OUTPUT_MODELS

_TARGET = (
    Path(__file__).resolve().parents[2]
    / "frontend" / "src" / "lib" / "api" / "mcp-schema.json"
)


def build_document() -> dict:
    """The schema document, as a dict. One `$defs` block shared by all tools."""
    models = [(m, "validation") for m in dict.fromkeys(TOOL_OUTPUT_MODELS.values())]
    defs_by_model, top = models_json_schema(models, ref_template="#/$defs/{model}")
    # `top` holds {"$defs": {...}}. Build a stable properties map name -> $ref.
    properties = {
        name: defs_by_model[(model, "validation")]
        for name, model in sorted(TOOL_OUTPUT_MODELS.items())
    }
    return {
        "$schema": GenerateJsonSchema.schema_dialect,
        "title": "MCPToolOutputs",
        "description": "Generated by backend/mcp_server/dump_schemas.py - do not edit.",
        "type": "object",
        "properties": properties,
        "required": sorted(TOOL_OUTPUT_MODELS),
        "additionalProperties": False,
        "$defs": top.get("$defs", {}),
    }


def render() -> str:
    """The exact bytes written to disk (and compared in the drift test)."""
    return json.dumps(build_document(), indent=2, sort_keys=True) + "\n"


def main() -> None:
    _TARGET.write_text(render(), encoding="utf-8")
    print(f"wrote {_TARGET}")


if __name__ == "__main__":
    main()
